version: 2

project_name: awsctf

builds:
  - id: awsctf
    main: .
    binary: awsctf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

release:
  github:
    owner: AmulThantharate
    name: awsctf
  draft: false
  prerelease: false
  name_template: "v{{ .Version }}"

dockers:
  - image_templates:
      - "ghcr.io/amulthantharate/awsctf:{{ .Version }}"
      - "ghcr.io/amulthantharate/awsctf:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.source=https://github.com/amulthantharate/awsctf"
      - "--label=org.opencontainers.image.description=AWSCTF Range CLI"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
