version: 2

project_name: awsctf

builds:
  - id: awsctf
    main: .
    binary: awsctf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

release:
  github:
    owner: AmulThantharate
    name: awsctf
  draft: false
  prerelease: false
  name_template: "v{{ .Version }}"
